controllers:
    resource: ../../src/Controller/
    type: annotation

# toutes les routes définies dans les contôleurs contenus dans le répertoire Admin sont préfixées par /admin
admin:
    resource: ../../src/Controller/Admin/
    type: annotation
    prefix: /admin